version: 2
jobs:
  build:
    working_directory: ~/ProjectBootstrap
    docker:
      - image: egis/build-slave
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: pre-requisites
          command: |
            pip install --user cookiecutter
            npm install -g yarn
            yarn

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.cache/yarn
            - yarn.lock

      - run:
          name: generate a test plugin project
          command: |
            cd ..
            ~/.local/bin/cookiecutter ./ProjectBootstrap name=BootstrappedIronMan directory_name=BootstrappedIronMan

      - run:
          name: push the test plugin project to github
          command: |
            git config --global user.email circleci@circleci
            git config --global user.name CircleCI
            cd ..
            ./node_modules/gh-pages/bin/gh-pages -d BootstrappedIronMan -b generated-project-test

      - run:
          name: run the build for test plugin project
          command: |
            curl --user ${CIRCLE_API_TOKEN}: \
              --header "Content-Type: application/json" \
              --data '{"build_parameters": {"CIRCLE_JOB": "build", "NPM_TOKEN": "${NPM_TOKEN}"}}' \
              --data revision=$CIRCLE_SHA1 \
              --request POST \
              https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/generated-project-test

