version: 2
jobs:
  build:
    working_directory: ~/ProjectBootstrap
    machine: true
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-v1-{{ checksum "package.json" }}

      - run:
          name: pre-requisites
          command: |
            pip install --user cookiecutter
            npm install -g yarn
            yarn

      - save_cache:
          key: dependency-cache-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.cache/yarn
            - yarn.lock

      - run:
          name: generate a test plugin project
          command: |
            cd ..
            ~/.local/bin/cookiecutter --no-input ./ProjectBootstrap name=BootstrappedIronMan directory_name=BootstrappedIronMan
            cd BootstrappedIronMan

      - run:
          name: push the test plugin project to github
          command: |
            if [[ "$TEST_GENERATED_PROJECT" == "true" ]]; then
              git config --global user.email circleci@circleci
              git config --global user.name CircleCI
              ./node_modules/.bin/gh-pages --dist ../BootstrappedIronMan --branch generated-project-test --dotfiles --silent --repo "https://${GH_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git"
            fi
      - run:
          name: run the build for test plugin project
          command: |
            if [[ "$TEST_GENERATED_PROJECT" == "true" ]]; then
              curl --user ${CIRCLE_API_TOKEN}: \
                --header "Content-Type: application/json" \
                --data '{"build_parameters": {"CIRCLE_JOB": "build"}}' \
                --request POST \
                https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/generated-project-test > output
              export build_num="$(cat output | jq '.build_num')"
              cat output
              echo "build_num=${build_num}"
              .circleci/wait-for-build-status.sh
            fi

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: org-global
